repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6
        # We have to be specific here as python/lib contains a symlink
        # loop that throws an error before black excludes it
        args: [python/tskit, python/setup.py, python/stress_lowlevel.py]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [--config=python/.flake8]
