ignore:
  - "c/tests/"
  - "c/subprojects/**/*"

codecov:
  require_ci_to_pass: false

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment


component_management:
  individual_components:
    - component_id: python_code
      name: Python API
      paths:
        - python/tskit/*.py

    - component_id: python_c_code
      name: Python C interface
      paths:
        - python/_tskitmodule.c
        - python/lwt_interface/tskit_lwt_interface.h

    - component_id: c_code
      name: C library
      paths:
        - c
