name: Build Docs
on:
  pull_request:
  merge_group:
  push:
    branches: [main]
    tags:
      - '*'

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  Docs:
    uses: tskit-dev/.github/.github/workflows/docs.yml@v20
    with:
      pyproject-directory: python
      additional-apt-packages: doxygen
