name: Run mypy

on:
  push:
  pull_request:

jobs:
  OSX:
    runs-on: macos-latest
    strategy:
      matrix:
        python: ["3.10", 3.14]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install mypy
        run: |
          pip install mypy
      - name: Run mypy
        run: |
          mypy python

