name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies and set path
        run: |
            sudo apt-get update
            sudo apt-get install -y ninja-build libcunit1-dev python3-pip
            # Install meson as root so we can install to the system below.
            sudo pip install meson
      - name: Build tarball and changelogs
        run: |
          git rm -rf c/tests/meson-subproject
          git config --global user.email "CI@CI.com"
          git config --global user.name "Mr Robot"
          git add -A
          git commit -m "dummy commit to make meson not add in the symlinked directory"
          meson c build-gcc
          meson dist -C build-gcc
          python docs/convert_changelog.py c/CHANGELOG.rst > C-CHANGELOG.txt
          python docs/convert_changelog.py python/CHANGELOG.rst > PYTHON-CHANGELOG.txt
      - name: Get the version
        id: get_version
        run:
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: C Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && contains(github.event.ref, 'C_')
        with:
          name: C API ${{ steps.get_version.outputs.VERSION }}
          body_path: C-CHANGELOG.txt
          draft: True
          fail_on_unmatched_files: True
          files: build-gcc/meson-dist/*
      - name: Python Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && !contains(github.event.ref, 'C_')
        with:
          name: Python ${{ steps.get_version.outputs.VERSION }}
          body_path: PYTHON-CHANGELOG.txt
          draft: True
          fail_on_unmatched_files: True